# Generated by Django 5.2.6 on 2025-10-06 22:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyreport',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Optional image attachment for the safety report', max_length=255, null=True, verbose_name='image'),
        ),
    ]
